# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180228_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createad_date',
            new_name='created_date',
        ),
    ]
